CREATE TABLE Item(
	ItemID INTEGER NOT NULL,
	Name VARCHAR(200) NOT NULL,
	Seller VARCHAR(200) NOT NULL,
	BuyPrice DECIMAL(8,2) NOT NULL,
	FirstBid DECIMAL(8,2) NOT NULL,
	Currently DECIMAL(8,2) NOT NULL,
	NumberOfBids INTEGER(4) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	Description VARCHAR(4000) NOT NULL,
	
	PRIMARY KEY(ItemID)
);

CREATE TABLE User(
	UserID INTEGER NOT NULL,
	Rating INTEGER NOT NULL,
	Location VARCHAR(200) NOT NULL,
	Country VARCHAR(200) NOT NULL,
	
	PRIMARY KEY(UserID)
);


CREATE TABLE Category(
	ItemID INTEGER NOT NULL,
	Category VARCHAR(200) NOT NULL
);

CREATE TABLE Bid(
	UserID INTEGER NOT NULL,
	ItemID INTEGER NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,
	
	PRIMARY KEY(UserID, ItemID, Time)
	
);